# Use Node.js base image
FROM node:16-alpine AS development

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --unsafe-perm

# Copy the application source code
COPY . .

# Expose port and run the app
EXPOSE 3306
CMD ["npm", "start"]



